# Generated by Django 6.0.2 on 2026-03-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(related_name='books', to='authors.author')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
