# Generated by Django 6.0.2 on 2026-03-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NONFICTION', 'Non-Fiction'), ('SCIENCE', 'Science'), ('FANTASY', 'Fantasy'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='books', to='authors.author')),
            ],
            options={
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['publication_date'], name='books_book_publica_4f381a_idx'), models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx')],
            },
        ),
    ]
